"""Type stubs for auto_git module."""

from typing import Any

class AutoGit:
    """Git sync with event-driven debounce support."""
    
    def __init__(self, config_path: str = "config.yaml") -> None: ...
    
    @property
    def enabled(self) -> bool: ...
    
    @property
    def idle_minutes(self) -> int: ...
    
    @property
    def commit_prefix(self) -> str: ...
    
    @property
    def vault_path(self) -> str: ...
    
    def run_git_command(self, *args) -> tuple[bool, str]: ...
    
    def has_changes(self) -> bool: ...
    
    def sync(self) -> bool: ...
    
    def notify(self) -> None: ...
    
    def start(self) -> None: ...
    
    def stop(self) -> None: ...
    
    def run(self) -> None: ...
    
    @property
    def status(self) -> dict[str, Any]: ...
